"""added image to group, added missing fields to mebers

Revision ID: 746ee909aa4d
Revises: 540f3be81e34
Create Date: 2021-03-09 15:54:23.646914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746ee909aa4d'
down_revision = '540f3be81e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('accepted', sa.Boolean(), nullable=True))
    op.add_column('group_members', sa.Column('leader', sa.Boolean(), nullable=True))
    op.add_column('groups', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'image_url')
    op.drop_column('group_members', 'leader')
    op.drop_column('group_members', 'accepted')
    # ### end Alembic commands ###
