"""added gear category

Revision ID: f2f8e4ffbe80
Revises: 69d806439872
Create Date: 2021-03-04 14:35:46.194001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f8e4ffbe80'
down_revision = '69d806439872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gear_logs', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key('gear_logs_category_id_fkey',
                          'gear_logs', 'gear_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gear_logs_category_id_fkey',
                       'gear_logs', type_='foreignkey')
    op.drop_column('gear_logs', 'category_id')
    op.drop_table('gear_categories')
    # ### end Alembic commands ###
