"""added trip gear items

Revision ID: f70e605f7324
Revises: 42530289f343
Create Date: 2021-03-04 15:22:42.443154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70e605f7324'
down_revision = '42530289f343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_gear_items',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('gear_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gear_id'], ['gear_logs.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'gear_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_gear_items')
    # ### end Alembic commands ###
